run-dist:
	./build/install/app/bin/app
build:
	./gradlew clean build
install:
	./gradlew clean installDist
lint:
	./gradlew checkstyleMain
report:
	./gradlew jacocoTestReport
clean:
	./gradlew clean
test:
	./gradlew test
.PHONY: build